/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppNotification {
  'notifType' : string,
  'notifId' : string,
  'isRead' : boolean,
  'message' : string,
  'timestamp' : Timestamp,
}
export interface Appointment {
  'id' : bigint,
  'status' : AppointmentStatus,
  'userId' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'preferredDatetime' : string,
  'diseaseName' : string,
  'severity' : SeverityLevel,
  'phone' : string,
  'location' : string,
}
export interface AppointmentInput {
  'name' : string,
  'preferredDatetime' : string,
  'diseaseName' : string,
  'severity' : SeverityLevel,
  'phone' : string,
  'location' : string,
}
export type AppointmentStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'confirmed' : null };
export interface ChatMessage {
  'id' : bigint,
  'userId' : UserId,
  'role' : ChatRole,
  'message' : string,
  'timestamp' : Timestamp,
}
export type ChatRole = { 'user' : null } |
  { 'assistant' : null };
export interface CropCalendarEntry {
  'region' : string,
  'harvestMonths' : Array<bigint>,
  'growthDuration' : bigint,
  'sowingMonths' : Array<bigint>,
  'notes' : string,
  'cropType' : string,
}
export interface DiseaseRecord {
  'id' : bigint,
  'plantType' : string,
  'severityLevel' : SeverityLevel,
  'cause' : string,
  'name' : string,
  'preventionSteps' : Array<string>,
  'medicationNames' : Array<string>,
  'treatmentSteps' : Array<string>,
}
export interface DiseaseSeverityEntry {
  'count' : bigint,
  'diseaseName' : string,
}
export interface ExpertContact {
  'id' : string,
  'region' : string,
  'name' : string,
  'email' : string,
  'district' : string,
  'available' : boolean,
  'specialization' : string,
  'phone' : string,
}
export type ExternalBlob = Uint8Array;
export interface FertilizerGuide {
  'npkRatio' : string,
  'growthStage' : string,
  'applicationTiming' : string,
  'notes' : string,
  'organicOptions' : Array<string>,
  'cropType' : string,
  'soilPhRange' : string,
}
export interface ForumLeaderboardEntry {
  'postCount' : bigint,
  'displayName' : string,
  'userId' : UserId,
  'score' : bigint,
  'totalLikes' : bigint,
}
export interface ForumPost {
  'id' : string,
  'title' : string,
  'body' : string,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'tags' : Array<string>,
  'authorName' : string,
  'updatedAt' : Timestamp,
  'cropType' : string,
  'likesCount' : bigint,
}
export interface ForumReply {
  'id' : string,
  'body' : string,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'authorName' : string,
  'likesCount' : bigint,
  'postId' : string,
}
export interface PredictionInput {
  'imageBlob' : ExternalBlob,
  'plantType' : string,
}
export interface PredictionRecord {
  'id' : bigint,
  'imageBlob' : ExternalBlob,
  'severityLevel' : SeverityLevel,
  'userId' : UserId,
  'confidenceScore' : number,
  'diseaseName' : string,
  'timestamp' : Timestamp,
}
export type SeverityLevel = { 'mild' : null } |
  { 'severe' : null } |
  { 'moderate' : null };
export interface SuccessStory {
  'id' : string,
  'afterDescription' : string,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'authorName' : string,
  'photoUrl' : [] | [string],
  'diseaseName' : string,
  'cropType' : string,
  'beforeDescription' : string,
  'likesCount' : bigint,
  'treatmentUsed' : string,
}
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface TreatmentReminder {
  'id' : string,
  'predictionId' : string,
  'userId' : UserId,
  'note' : string,
  'createdAt' : Timestamp,
  'completed' : boolean,
  'reminderDate' : Timestamp,
  'diseaseName' : string,
}
export type UserId = Principal;
export interface UserProfile {
  'regionAlerts' : Array<[string, boolean]>,
  'userId' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface YieldEstimation {
  'areaHectares' : number,
  'healthStatus' : string,
  'notes' : string,
  'cropType' : string,
  'estimatedYieldKg' : number,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addExpertContact' : ActorMethod<
    [string, string, string, string, string, string, boolean],
    ExpertContact
  >,
  'addReminder' : ActorMethod<
    [string, string, Timestamp, string],
    TreatmentReminder
  >,
  'admin_setHuggingFaceKey' : ActorMethod<[string], undefined>,
  'admin_setOpenAiKey' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookAppointment' : ActorMethod<[AppointmentInput], Appointment>,
  'clearChatHistory' : ActorMethod<[], undefined>,
  'completeReminder' : ActorMethod<[string], boolean>,
  'createForumPost' : ActorMethod<
    [string, string, string, string, Array<string>],
    ForumPost
  >,
  'createSuccessStory' : ActorMethod<
    [string, string, string, string, string, string, [] | [string]],
    SuccessStory
  >,
  'estimateYield' : ActorMethod<[string, number, string], YieldEstimation>,
  'getAppointments' : ActorMethod<[], Array<Appointment>>,
  'getCallerAlertSettings' : ActorMethod<[], Array<[string, boolean]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChatHistory' : ActorMethod<[], Array<ChatMessage>>,
  'getCropCalendar' : ActorMethod<[string], [] | [CropCalendarEntry]>,
  'getDiseaseRecord' : ActorMethod<[string], [] | [DiseaseRecord]>,
  'getDiseaseSeverityMap' : ActorMethod<[], Array<DiseaseSeverityEntry>>,
  'getExpertContacts' : ActorMethod<[string], Array<ExpertContact>>,
  'getFertilizerGuide' : ActorMethod<[string, string], [] | [FertilizerGuide]>,
  'getForumLeaderboard' : ActorMethod<[], Array<ForumLeaderboardEntry>>,
  'getForumPost' : ActorMethod<[string], [] | [ForumPost]>,
  'getForumPosts' : ActorMethod<[bigint, bigint], Array<ForumPost>>,
  'getNotifications' : ActorMethod<[], Array<AppNotification>>,
  'getPredictionHistory' : ActorMethod<[], Array<PredictionRecord>>,
  'getReminders' : ActorMethod<[], Array<TreatmentReminder>>,
  'getReplies' : ActorMethod<[string], Array<ForumReply>>,
  'getSuccessStories' : ActorMethod<[], Array<SuccessStory>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likePost' : ActorMethod<[string], boolean>,
  'likeSuccessStory' : ActorMethod<[string], boolean>,
  'listDiseaseRecords' : ActorMethod<[], Array<DiseaseRecord>>,
  'markNotificationRead' : ActorMethod<[string], undefined>,
  'predictDiseaseFromImage' : ActorMethod<
    [string, string, ExternalBlob],
    PredictionRecord
  >,
  'replyToPost' : ActorMethod<[string, string, string], ForumReply>,
  'saveCallerAlertSettings' : ActorMethod<
    [Array<[string, boolean]>],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[string], undefined>,
  'saveChatMessage' : ActorMethod<[string, ChatRole], ChatMessage>,
  'savePrediction' : ActorMethod<
    [PredictionInput, string, number, SeverityLevel],
    PredictionRecord
  >,
  'sendChatMessage' : ActorMethod<[string], string>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAppointmentStatus' : ActorMethod<[bigint, AppointmentStatus], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];