/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExpertContact = IDL.Record({
  'id' : IDL.Text,
  'region' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'district' : IDL.Text,
  'available' : IDL.Bool,
  'specialization' : IDL.Text,
  'phone' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const UserId = IDL.Principal;
export const TreatmentReminder = IDL.Record({
  'id' : IDL.Text,
  'predictionId' : IDL.Text,
  'userId' : UserId,
  'note' : IDL.Text,
  'createdAt' : Timestamp,
  'completed' : IDL.Bool,
  'reminderDate' : Timestamp,
  'diseaseName' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SeverityLevel = IDL.Variant({
  'mild' : IDL.Null,
  'severe' : IDL.Null,
  'moderate' : IDL.Null,
});
export const AppointmentInput = IDL.Record({
  'name' : IDL.Text,
  'preferredDatetime' : IDL.Text,
  'diseaseName' : IDL.Text,
  'severity' : SeverityLevel,
  'phone' : IDL.Text,
  'location' : IDL.Text,
});
export const AppointmentStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Appointment = IDL.Record({
  'id' : IDL.Nat,
  'status' : AppointmentStatus,
  'userId' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'preferredDatetime' : IDL.Text,
  'diseaseName' : IDL.Text,
  'severity' : SeverityLevel,
  'phone' : IDL.Text,
  'location' : IDL.Text,
});
export const ForumPost = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'tags' : IDL.Vec(IDL.Text),
  'authorName' : IDL.Text,
  'updatedAt' : Timestamp,
  'cropType' : IDL.Text,
  'likesCount' : IDL.Nat,
});
export const SuccessStory = IDL.Record({
  'id' : IDL.Text,
  'afterDescription' : IDL.Text,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'authorName' : IDL.Text,
  'photoUrl' : IDL.Opt(IDL.Text),
  'diseaseName' : IDL.Text,
  'cropType' : IDL.Text,
  'beforeDescription' : IDL.Text,
  'likesCount' : IDL.Nat,
  'treatmentUsed' : IDL.Text,
});
export const YieldEstimation = IDL.Record({
  'areaHectares' : IDL.Float64,
  'healthStatus' : IDL.Text,
  'notes' : IDL.Text,
  'cropType' : IDL.Text,
  'estimatedYieldKg' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'regionAlerts' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool)),
  'userId' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
});
export const ChatRole = IDL.Variant({
  'user' : IDL.Null,
  'assistant' : IDL.Null,
});
export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'userId' : UserId,
  'role' : ChatRole,
  'message' : IDL.Text,
  'timestamp' : Timestamp,
});
export const CropCalendarEntry = IDL.Record({
  'region' : IDL.Text,
  'harvestMonths' : IDL.Vec(IDL.Nat),
  'growthDuration' : IDL.Nat,
  'sowingMonths' : IDL.Vec(IDL.Nat),
  'notes' : IDL.Text,
  'cropType' : IDL.Text,
});
export const DiseaseRecord = IDL.Record({
  'id' : IDL.Nat,
  'plantType' : IDL.Text,
  'severityLevel' : SeverityLevel,
  'cause' : IDL.Text,
  'name' : IDL.Text,
  'preventionSteps' : IDL.Vec(IDL.Text),
  'medicationNames' : IDL.Vec(IDL.Text),
  'treatmentSteps' : IDL.Vec(IDL.Text),
});
export const DiseaseSeverityEntry = IDL.Record({
  'count' : IDL.Nat,
  'diseaseName' : IDL.Text,
});
export const FertilizerGuide = IDL.Record({
  'npkRatio' : IDL.Text,
  'growthStage' : IDL.Text,
  'applicationTiming' : IDL.Text,
  'notes' : IDL.Text,
  'organicOptions' : IDL.Vec(IDL.Text),
  'cropType' : IDL.Text,
  'soilPhRange' : IDL.Text,
});
export const ForumLeaderboardEntry = IDL.Record({
  'postCount' : IDL.Nat,
  'displayName' : IDL.Text,
  'userId' : UserId,
  'score' : IDL.Nat,
  'totalLikes' : IDL.Nat,
});
export const AppNotification = IDL.Record({
  'notifType' : IDL.Text,
  'notifId' : IDL.Text,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : Timestamp,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PredictionRecord = IDL.Record({
  'id' : IDL.Nat,
  'imageBlob' : ExternalBlob,
  'severityLevel' : SeverityLevel,
  'userId' : UserId,
  'confidenceScore' : IDL.Float64,
  'diseaseName' : IDL.Text,
  'timestamp' : Timestamp,
});
export const ForumReply = IDL.Record({
  'id' : IDL.Text,
  'body' : IDL.Text,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'authorName' : IDL.Text,
  'likesCount' : IDL.Nat,
  'postId' : IDL.Text,
});
export const PredictionInput = IDL.Record({
  'imageBlob' : ExternalBlob,
  'plantType' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addExpertContact' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [ExpertContact],
      [],
    ),
  'addReminder' : IDL.Func(
      [IDL.Text, IDL.Text, Timestamp, IDL.Text],
      [TreatmentReminder],
      [],
    ),
  'admin_setHuggingFaceKey' : IDL.Func([IDL.Text], [], []),
  'admin_setOpenAiKey' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookAppointment' : IDL.Func([AppointmentInput], [Appointment], []),
  'clearChatHistory' : IDL.Func([], [], []),
  'completeReminder' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'createForumPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [ForumPost],
      [],
    ),
  'createSuccessStory' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [SuccessStory],
      [],
    ),
  'estimateYield' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Text],
      [YieldEstimation],
      ['query'],
    ),
  'getAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getCallerAlertSettings' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChatHistory' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getCropCalendar' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(CropCalendarEntry)],
      ['query'],
    ),
  'getDiseaseRecord' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(DiseaseRecord)],
      ['query'],
    ),
  'getDiseaseSeverityMap' : IDL.Func(
      [],
      [IDL.Vec(DiseaseSeverityEntry)],
      ['query'],
    ),
  'getExpertContacts' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ExpertContact)],
      ['query'],
    ),
  'getFertilizerGuide' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(FertilizerGuide)],
      ['query'],
    ),
  'getForumLeaderboard' : IDL.Func(
      [],
      [IDL.Vec(ForumLeaderboardEntry)],
      ['query'],
    ),
  'getForumPost' : IDL.Func([IDL.Text], [IDL.Opt(ForumPost)], ['query']),
  'getForumPosts' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(ForumPost)],
      ['query'],
    ),
  'getNotifications' : IDL.Func([], [IDL.Vec(AppNotification)], ['query']),
  'getPredictionHistory' : IDL.Func([], [IDL.Vec(PredictionRecord)], ['query']),
  'getReminders' : IDL.Func([], [IDL.Vec(TreatmentReminder)], ['query']),
  'getReplies' : IDL.Func([IDL.Text], [IDL.Vec(ForumReply)], ['query']),
  'getSuccessStories' : IDL.Func([], [IDL.Vec(SuccessStory)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likePost' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'likeSuccessStory' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'listDiseaseRecords' : IDL.Func([], [IDL.Vec(DiseaseRecord)], ['query']),
  'markNotificationRead' : IDL.Func([IDL.Text], [], []),
  'predictDiseaseFromImage' : IDL.Func(
      [IDL.Text, IDL.Text, ExternalBlob],
      [PredictionRecord],
      [],
    ),
  'replyToPost' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [ForumReply], []),
  'saveCallerAlertSettings' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool))],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([IDL.Text], [], []),
  'saveChatMessage' : IDL.Func([IDL.Text, ChatRole], [ChatMessage], []),
  'savePrediction' : IDL.Func(
      [PredictionInput, IDL.Text, IDL.Float64, SeverityLevel],
      [PredictionRecord],
      [],
    ),
  'sendChatMessage' : IDL.Func([IDL.Text], [IDL.Text], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateAppointmentStatus' : IDL.Func(
      [IDL.Nat, AppointmentStatus],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExpertContact = IDL.Record({
    'id' : IDL.Text,
    'region' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'district' : IDL.Text,
    'available' : IDL.Bool,
    'specialization' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const UserId = IDL.Principal;
  const TreatmentReminder = IDL.Record({
    'id' : IDL.Text,
    'predictionId' : IDL.Text,
    'userId' : UserId,
    'note' : IDL.Text,
    'createdAt' : Timestamp,
    'completed' : IDL.Bool,
    'reminderDate' : Timestamp,
    'diseaseName' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SeverityLevel = IDL.Variant({
    'mild' : IDL.Null,
    'severe' : IDL.Null,
    'moderate' : IDL.Null,
  });
  const AppointmentInput = IDL.Record({
    'name' : IDL.Text,
    'preferredDatetime' : IDL.Text,
    'diseaseName' : IDL.Text,
    'severity' : SeverityLevel,
    'phone' : IDL.Text,
    'location' : IDL.Text,
  });
  const AppointmentStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Appointment = IDL.Record({
    'id' : IDL.Nat,
    'status' : AppointmentStatus,
    'userId' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'preferredDatetime' : IDL.Text,
    'diseaseName' : IDL.Text,
    'severity' : SeverityLevel,
    'phone' : IDL.Text,
    'location' : IDL.Text,
  });
  const ForumPost = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'tags' : IDL.Vec(IDL.Text),
    'authorName' : IDL.Text,
    'updatedAt' : Timestamp,
    'cropType' : IDL.Text,
    'likesCount' : IDL.Nat,
  });
  const SuccessStory = IDL.Record({
    'id' : IDL.Text,
    'afterDescription' : IDL.Text,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'authorName' : IDL.Text,
    'photoUrl' : IDL.Opt(IDL.Text),
    'diseaseName' : IDL.Text,
    'cropType' : IDL.Text,
    'beforeDescription' : IDL.Text,
    'likesCount' : IDL.Nat,
    'treatmentUsed' : IDL.Text,
  });
  const YieldEstimation = IDL.Record({
    'areaHectares' : IDL.Float64,
    'healthStatus' : IDL.Text,
    'notes' : IDL.Text,
    'cropType' : IDL.Text,
    'estimatedYieldKg' : IDL.Float64,
  });
  const UserProfile = IDL.Record({
    'regionAlerts' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool)),
    'userId' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
  });
  const ChatRole = IDL.Variant({ 'user' : IDL.Null, 'assistant' : IDL.Null });
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'userId' : UserId,
    'role' : ChatRole,
    'message' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const CropCalendarEntry = IDL.Record({
    'region' : IDL.Text,
    'harvestMonths' : IDL.Vec(IDL.Nat),
    'growthDuration' : IDL.Nat,
    'sowingMonths' : IDL.Vec(IDL.Nat),
    'notes' : IDL.Text,
    'cropType' : IDL.Text,
  });
  const DiseaseRecord = IDL.Record({
    'id' : IDL.Nat,
    'plantType' : IDL.Text,
    'severityLevel' : SeverityLevel,
    'cause' : IDL.Text,
    'name' : IDL.Text,
    'preventionSteps' : IDL.Vec(IDL.Text),
    'medicationNames' : IDL.Vec(IDL.Text),
    'treatmentSteps' : IDL.Vec(IDL.Text),
  });
  const DiseaseSeverityEntry = IDL.Record({
    'count' : IDL.Nat,
    'diseaseName' : IDL.Text,
  });
  const FertilizerGuide = IDL.Record({
    'npkRatio' : IDL.Text,
    'growthStage' : IDL.Text,
    'applicationTiming' : IDL.Text,
    'notes' : IDL.Text,
    'organicOptions' : IDL.Vec(IDL.Text),
    'cropType' : IDL.Text,
    'soilPhRange' : IDL.Text,
  });
  const ForumLeaderboardEntry = IDL.Record({
    'postCount' : IDL.Nat,
    'displayName' : IDL.Text,
    'userId' : UserId,
    'score' : IDL.Nat,
    'totalLikes' : IDL.Nat,
  });
  const AppNotification = IDL.Record({
    'notifType' : IDL.Text,
    'notifId' : IDL.Text,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PredictionRecord = IDL.Record({
    'id' : IDL.Nat,
    'imageBlob' : ExternalBlob,
    'severityLevel' : SeverityLevel,
    'userId' : UserId,
    'confidenceScore' : IDL.Float64,
    'diseaseName' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const ForumReply = IDL.Record({
    'id' : IDL.Text,
    'body' : IDL.Text,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'authorName' : IDL.Text,
    'likesCount' : IDL.Nat,
    'postId' : IDL.Text,
  });
  const PredictionInput = IDL.Record({
    'imageBlob' : ExternalBlob,
    'plantType' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addExpertContact' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [ExpertContact],
        [],
      ),
    'addReminder' : IDL.Func(
        [IDL.Text, IDL.Text, Timestamp, IDL.Text],
        [TreatmentReminder],
        [],
      ),
    'admin_setHuggingFaceKey' : IDL.Func([IDL.Text], [], []),
    'admin_setOpenAiKey' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookAppointment' : IDL.Func([AppointmentInput], [Appointment], []),
    'clearChatHistory' : IDL.Func([], [], []),
    'completeReminder' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'createForumPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [ForumPost],
        [],
      ),
    'createSuccessStory' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [SuccessStory],
        [],
      ),
    'estimateYield' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Text],
        [YieldEstimation],
        ['query'],
      ),
    'getAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getCallerAlertSettings' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChatHistory' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getCropCalendar' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CropCalendarEntry)],
        ['query'],
      ),
    'getDiseaseRecord' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(DiseaseRecord)],
        ['query'],
      ),
    'getDiseaseSeverityMap' : IDL.Func(
        [],
        [IDL.Vec(DiseaseSeverityEntry)],
        ['query'],
      ),
    'getExpertContacts' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ExpertContact)],
        ['query'],
      ),
    'getFertilizerGuide' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(FertilizerGuide)],
        ['query'],
      ),
    'getForumLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(ForumLeaderboardEntry)],
        ['query'],
      ),
    'getForumPost' : IDL.Func([IDL.Text], [IDL.Opt(ForumPost)], ['query']),
    'getForumPosts' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(ForumPost)],
        ['query'],
      ),
    'getNotifications' : IDL.Func([], [IDL.Vec(AppNotification)], ['query']),
    'getPredictionHistory' : IDL.Func(
        [],
        [IDL.Vec(PredictionRecord)],
        ['query'],
      ),
    'getReminders' : IDL.Func([], [IDL.Vec(TreatmentReminder)], ['query']),
    'getReplies' : IDL.Func([IDL.Text], [IDL.Vec(ForumReply)], ['query']),
    'getSuccessStories' : IDL.Func([], [IDL.Vec(SuccessStory)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likePost' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'likeSuccessStory' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'listDiseaseRecords' : IDL.Func([], [IDL.Vec(DiseaseRecord)], ['query']),
    'markNotificationRead' : IDL.Func([IDL.Text], [], []),
    'predictDiseaseFromImage' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob],
        [PredictionRecord],
        [],
      ),
    'replyToPost' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [ForumReply], []),
    'saveCallerAlertSettings' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool))],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([IDL.Text], [], []),
    'saveChatMessage' : IDL.Func([IDL.Text, ChatRole], [ChatMessage], []),
    'savePrediction' : IDL.Func(
        [PredictionInput, IDL.Text, IDL.Float64, SeverityLevel],
        [PredictionRecord],
        [],
      ),
    'sendChatMessage' : IDL.Func([IDL.Text], [IDL.Text], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateAppointmentStatus' : IDL.Func(
        [IDL.Nat, AppointmentStatus],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };