/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface FertilizerGuide {
    npkRatio: string;
    growthStage: string;
    applicationTiming: string;
    notes: string;
    organicOptions: Array<string>;
    cropType: string;
    soilPhRange: string;
}
export interface CropCalendarEntry {
    region: string;
    harvestMonths: Array<bigint>;
    growthDuration: bigint;
    sowingMonths: Array<bigint>;
    notes: string;
    cropType: string;
}
export interface ForumLeaderboardEntry {
    postCount: bigint;
    displayName: string;
    userId: UserId;
    score: bigint;
    totalLikes: bigint;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface AppNotification {
    notifType: string;
    notifId: string;
    isRead: boolean;
    message: string;
    timestamp: Timestamp;
}
export interface DiseaseSeverityEntry {
    count: bigint;
    diseaseName: string;
}
export interface ChatMessage {
    id: bigint;
    userId: UserId;
    role: ChatRole;
    message: string;
    timestamp: Timestamp;
}
export interface PredictionRecord {
    id: bigint;
    imageBlob: ExternalBlob;
    severityLevel: SeverityLevel;
    userId: UserId;
    confidenceScore: number;
    diseaseName: string;
    timestamp: Timestamp;
}
export interface SuccessStory {
    id: string;
    afterDescription: string;
    userId: UserId;
    createdAt: Timestamp;
    authorName: string;
    photoUrl?: string;
    diseaseName: string;
    cropType: string;
    beforeDescription: string;
    likesCount: bigint;
    treatmentUsed: string;
}
export interface AppointmentInput {
    name: string;
    preferredDatetime: string;
    diseaseName: string;
    severity: SeverityLevel;
    phone: string;
    location: string;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface TreatmentReminder {
    id: string;
    predictionId: string;
    userId: UserId;
    note: string;
    createdAt: Timestamp;
    completed: boolean;
    reminderDate: Timestamp;
    diseaseName: string;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface ForumReply {
    id: string;
    body: string;
    userId: UserId;
    createdAt: Timestamp;
    authorName: string;
    likesCount: bigint;
    postId: string;
}
export interface YieldEstimation {
    areaHectares: number;
    healthStatus: string;
    notes: string;
    cropType: string;
    estimatedYieldKg: number;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ForumPost {
    id: string;
    title: string;
    body: string;
    userId: UserId;
    createdAt: Timestamp;
    tags: Array<string>;
    authorName: string;
    updatedAt: Timestamp;
    cropType: string;
    likesCount: bigint;
}
export type UserId = Principal;
export interface ExpertContact {
    id: string;
    region: string;
    name: string;
    email: string;
    district: string;
    available: boolean;
    specialization: string;
    phone: string;
}
export interface PredictionInput {
    imageBlob: ExternalBlob;
    plantType: string;
}
export interface DiseaseRecord {
    id: bigint;
    plantType: string;
    severityLevel: SeverityLevel;
    cause: string;
    name: string;
    preventionSteps: Array<string>;
    medicationNames: Array<string>;
    treatmentSteps: Array<string>;
}
export interface Appointment {
    id: bigint;
    status: AppointmentStatus;
    userId: UserId;
    name: string;
    createdAt: Timestamp;
    preferredDatetime: string;
    diseaseName: string;
    severity: SeverityLevel;
    phone: string;
    location: string;
}
export interface UserProfile {
    regionAlerts: Array<[string, boolean]>;
    userId: UserId;
    name: string;
    createdAt: Timestamp;
}
export enum AppointmentStatus {
    cancelled = "cancelled",
    pending = "pending",
    confirmed = "confirmed"
}
export enum ChatRole {
    user = "user",
    assistant = "assistant"
}
export enum SeverityLevel {
    mild = "mild",
    severe = "severe",
    moderate = "moderate"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    addExpertContact(name: string, region: string, district: string, phone: string, email: string, specialization: string, available: boolean): Promise<ExpertContact>;
    addReminder(predictionId: string, diseaseName: string, reminderDate: Timestamp, note: string): Promise<TreatmentReminder>;
    admin_setHuggingFaceKey(key: string): Promise<void>;
    admin_setOpenAiKey(key: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bookAppointment(input: AppointmentInput): Promise<Appointment>;
    clearChatHistory(): Promise<void>;
    completeReminder(reminderId: string): Promise<boolean>;
    createForumPost(authorName: string, title: string, body: string, cropType: string, tags: Array<string>): Promise<ForumPost>;
    createSuccessStory(authorName: string, cropType: string, diseaseName: string, beforeDescription: string, afterDescription: string, treatmentUsed: string, photoUrl: string | null): Promise<SuccessStory>;
    estimateYield(cropType: string, areaHectares: number, healthStatus: string): Promise<YieldEstimation>;
    getAppointments(): Promise<Array<Appointment>>;
    getCallerAlertSettings(): Promise<Array<[string, boolean]>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChatHistory(): Promise<Array<ChatMessage>>;
    getCropCalendar(cropType: string): Promise<CropCalendarEntry | null>;
    getDiseaseRecord(name: string): Promise<DiseaseRecord | null>;
    getDiseaseSeverityMap(): Promise<Array<DiseaseSeverityEntry>>;
    getExpertContacts(region: string): Promise<Array<ExpertContact>>;
    getFertilizerGuide(cropType: string, growthStage: string): Promise<FertilizerGuide | null>;
    getForumLeaderboard(): Promise<Array<ForumLeaderboardEntry>>;
    getForumPost(postId: string): Promise<ForumPost | null>;
    getForumPosts(offset: bigint, limit: bigint): Promise<Array<ForumPost>>;
    getNotifications(): Promise<Array<AppNotification>>;
    getPredictionHistory(): Promise<Array<PredictionRecord>>;
    getReminders(): Promise<Array<TreatmentReminder>>;
    getReplies(postId: string): Promise<Array<ForumReply>>;
    getSuccessStories(): Promise<Array<SuccessStory>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    likePost(postId: string): Promise<boolean>;
    likeSuccessStory(storyId: string): Promise<boolean>;
    listDiseaseRecords(): Promise<Array<DiseaseRecord>>;
    markNotificationRead(notifId: string): Promise<void>;
    predictDiseaseFromImage(imageBase64: string, plantType: string, imageBlob: ExternalBlob): Promise<PredictionRecord>;
    replyToPost(postId: string, authorName: string, body: string): Promise<ForumReply>;
    saveCallerAlertSettings(alerts: Array<[string, boolean]>): Promise<void>;
    saveCallerUserProfile(name: string): Promise<void>;
    saveChatMessage(message: string, role: ChatRole): Promise<ChatMessage>;
    savePrediction(input: PredictionInput, diseaseName: string, confidenceScore: number, severityLevel: SeverityLevel): Promise<PredictionRecord>;
    sendChatMessage(userMessage: string): Promise<string>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateAppointmentStatus(id: bigint, status: AppointmentStatus): Promise<boolean>;
}
import type { Appointment as _Appointment, AppointmentInput as _AppointmentInput, AppointmentStatus as _AppointmentStatus, ChatMessage as _ChatMessage, ChatRole as _ChatRole, CropCalendarEntry as _CropCalendarEntry, DiseaseRecord as _DiseaseRecord, ExternalBlob as _ExternalBlob, FertilizerGuide as _FertilizerGuide, ForumPost as _ForumPost, PredictionInput as _PredictionInput, PredictionRecord as _PredictionRecord, SeverityLevel as _SeverityLevel, SuccessStory as _SuccessStory, Timestamp as _Timestamp, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addExpertContact(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: boolean): Promise<ExpertContact> {
        if (this.processError) {
            try {
                const result = await this.actor.addExpertContact(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExpertContact(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async addReminder(arg0: string, arg1: string, arg2: Timestamp, arg3: string): Promise<TreatmentReminder> {
        if (this.processError) {
            try {
                const result = await this.actor.addReminder(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReminder(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async admin_setHuggingFaceKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.admin_setHuggingFaceKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.admin_setHuggingFaceKey(arg0);
            return result;
        }
    }
    async admin_setOpenAiKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.admin_setOpenAiKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.admin_setOpenAiKey(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bookAppointment(arg0: AppointmentInput): Promise<Appointment> {
        if (this.processError) {
            try {
                const result = await this.actor.bookAppointment(to_candid_AppointmentInput_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Appointment_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookAppointment(to_candid_AppointmentInput_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Appointment_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async clearChatHistory(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearChatHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearChatHistory();
            return result;
        }
    }
    async completeReminder(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.completeReminder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeReminder(arg0);
            return result;
        }
    }
    async createForumPost(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Array<string>): Promise<ForumPost> {
        if (this.processError) {
            try {
                const result = await this.actor.createForumPost(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createForumPost(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createSuccessStory(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string | null): Promise<SuccessStory> {
        if (this.processError) {
            try {
                const result = await this.actor.createSuccessStory(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n20(this._uploadFile, this._downloadFile, arg6));
                return from_candid_SuccessStory_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSuccessStory(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n20(this._uploadFile, this._downloadFile, arg6));
            return from_candid_SuccessStory_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async estimateYield(arg0: string, arg1: number, arg2: string): Promise<YieldEstimation> {
        if (this.processError) {
            try {
                const result = await this.actor.estimateYield(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.estimateYield(arg0, arg1, arg2);
            return result;
        }
    }
    async getAppointments(): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointments();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointments();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerAlertSettings(): Promise<Array<[string, boolean]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerAlertSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerAlertSettings();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChatHistory(): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatHistory();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatHistory();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCropCalendar(arg0: string): Promise<CropCalendarEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCropCalendar(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCropCalendar(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDiseaseRecord(arg0: string): Promise<DiseaseRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDiseaseRecord(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDiseaseRecord(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDiseaseSeverityMap(): Promise<Array<DiseaseSeverityEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDiseaseSeverityMap();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDiseaseSeverityMap();
            return result;
        }
    }
    async getExpertContacts(arg0: string): Promise<Array<ExpertContact>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpertContacts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpertContacts(arg0);
            return result;
        }
    }
    async getFertilizerGuide(arg0: string, arg1: string): Promise<FertilizerGuide | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFertilizerGuide(arg0, arg1);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFertilizerGuide(arg0, arg1);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getForumLeaderboard(): Promise<Array<ForumLeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getForumLeaderboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getForumLeaderboard();
            return result;
        }
    }
    async getForumPost(arg0: string): Promise<ForumPost | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getForumPost(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getForumPost(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getForumPosts(arg0: bigint, arg1: bigint): Promise<Array<ForumPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getForumPosts(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getForumPosts(arg0, arg1);
            return result;
        }
    }
    async getNotifications(): Promise<Array<AppNotification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications();
            return result;
        }
    }
    async getPredictionHistory(): Promise<Array<PredictionRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPredictionHistory();
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPredictionHistory();
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReminders(): Promise<Array<TreatmentReminder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReminders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReminders();
            return result;
        }
    }
    async getReplies(arg0: string): Promise<Array<ForumReply>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReplies(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReplies(arg0);
            return result;
        }
    }
    async getSuccessStories(): Promise<Array<SuccessStory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSuccessStories();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSuccessStories();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async likePost(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.likePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likePost(arg0);
            return result;
        }
    }
    async likeSuccessStory(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.likeSuccessStory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likeSuccessStory(arg0);
            return result;
        }
    }
    async listDiseaseRecords(): Promise<Array<DiseaseRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDiseaseRecords();
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDiseaseRecords();
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async markNotificationRead(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationRead(arg0);
            return result;
        }
    }
    async predictDiseaseFromImage(arg0: string, arg1: string, arg2: ExternalBlob): Promise<PredictionRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.predictDiseaseFromImage(arg0, arg1, await to_candid_ExternalBlob_n45(this._uploadFile, this._downloadFile, arg2));
                return from_candid_PredictionRecord_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.predictDiseaseFromImage(arg0, arg1, await to_candid_ExternalBlob_n45(this._uploadFile, this._downloadFile, arg2));
            return from_candid_PredictionRecord_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async replyToPost(arg0: string, arg1: string, arg2: string): Promise<ForumReply> {
        if (this.processError) {
            try {
                const result = await this.actor.replyToPost(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.replyToPost(arg0, arg1, arg2);
            return result;
        }
    }
    async saveCallerAlertSettings(arg0: Array<[string, boolean]>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerAlertSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerAlertSettings(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveChatMessage(arg0: string, arg1: ChatRole): Promise<ChatMessage> {
        if (this.processError) {
            try {
                const result = await this.actor.saveChatMessage(arg0, to_candid_ChatRole_n46(this._uploadFile, this._downloadFile, arg1));
                return from_candid_ChatMessage_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveChatMessage(arg0, to_candid_ChatRole_n46(this._uploadFile, this._downloadFile, arg1));
            return from_candid_ChatMessage_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async savePrediction(arg0: PredictionInput, arg1: string, arg2: number, arg3: SeverityLevel): Promise<PredictionRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.savePrediction(await to_candid_PredictionInput_n48(this._uploadFile, this._downloadFile, arg0), arg1, arg2, to_candid_SeverityLevel_n12(this._uploadFile, this._downloadFile, arg3));
                return from_candid_PredictionRecord_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePrediction(await to_candid_PredictionInput_n48(this._uploadFile, this._downloadFile, arg0), arg1, arg2, to_candid_SeverityLevel_n12(this._uploadFile, this._downloadFile, arg3));
            return from_candid_PredictionRecord_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendChatMessage(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.sendChatMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendChatMessage(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateAppointmentStatus(arg0: bigint, arg1: AppointmentStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAppointmentStatus(arg0, to_candid_AppointmentStatus_n50(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAppointmentStatus(arg0, to_candid_AppointmentStatus_n50(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_AppointmentStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppointmentStatus): AppointmentStatus {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Appointment_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Appointment): Appointment {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_ChatMessage_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatMessage): ChatMessage {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_ChatRole_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatRole): ChatRole {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_DiseaseRecord_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DiseaseRecord): DiseaseRecord {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_PredictionRecord_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PredictionRecord): Promise<PredictionRecord> {
    return await from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_SeverityLevel_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SeverityLevel): SeverityLevel {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_SuccessStory_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SuccessStory): SuccessStory {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CropCalendarEntry]): CropCalendarEntry | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DiseaseRecord]): DiseaseRecord | null {
    return value.length === 0 ? null : from_candid_DiseaseRecord_n35(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FertilizerGuide]): FertilizerGuide | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ForumPost]): ForumPost | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _AppointmentStatus;
    userId: _UserId;
    name: string;
    createdAt: _Timestamp;
    preferredDatetime: string;
    diseaseName: string;
    severity: _SeverityLevel;
    phone: string;
    location: string;
}): {
    id: bigint;
    status: AppointmentStatus;
    userId: UserId;
    name: string;
    createdAt: Timestamp;
    preferredDatetime: string;
    diseaseName: string;
    severity: SeverityLevel;
    phone: string;
    location: string;
} {
    return {
        id: value.id,
        status: from_candid_AppointmentStatus_n16(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        name: value.name,
        createdAt: value.createdAt,
        preferredDatetime: value.preferredDatetime,
        diseaseName: value.diseaseName,
        severity: from_candid_SeverityLevel_n18(_uploadFile, _downloadFile, value.severity),
        phone: value.phone,
        location: value.location
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    afterDescription: string;
    userId: _UserId;
    createdAt: _Timestamp;
    authorName: string;
    photoUrl: [] | [string];
    diseaseName: string;
    cropType: string;
    beforeDescription: string;
    likesCount: bigint;
    treatmentUsed: string;
}): {
    id: string;
    afterDescription: string;
    userId: UserId;
    createdAt: Timestamp;
    authorName: string;
    photoUrl?: string;
    diseaseName: string;
    cropType: string;
    beforeDescription: string;
    likesCount: bigint;
    treatmentUsed: string;
} {
    return {
        id: value.id,
        afterDescription: value.afterDescription,
        userId: value.userId,
        createdAt: value.createdAt,
        authorName: value.authorName,
        photoUrl: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.photoUrl)),
        diseaseName: value.diseaseName,
        cropType: value.cropType,
        beforeDescription: value.beforeDescription,
        likesCount: value.likesCount,
        treatmentUsed: value.treatmentUsed
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    userId: _UserId;
    role: _ChatRole;
    message: string;
    timestamp: _Timestamp;
}): {
    id: bigint;
    userId: UserId;
    role: ChatRole;
    message: string;
    timestamp: Timestamp;
} {
    return {
        id: value.id,
        userId: value.userId,
        role: from_candid_ChatRole_n31(_uploadFile, _downloadFile, value.role),
        message: value.message,
        timestamp: value.timestamp
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    plantType: string;
    severityLevel: _SeverityLevel;
    cause: string;
    name: string;
    preventionSteps: Array<string>;
    medicationNames: Array<string>;
    treatmentSteps: Array<string>;
}): {
    id: bigint;
    plantType: string;
    severityLevel: SeverityLevel;
    cause: string;
    name: string;
    preventionSteps: Array<string>;
    medicationNames: Array<string>;
    treatmentSteps: Array<string>;
} {
    return {
        id: value.id,
        plantType: value.plantType,
        severityLevel: from_candid_SeverityLevel_n18(_uploadFile, _downloadFile, value.severityLevel),
        cause: value.cause,
        name: value.name,
        preventionSteps: value.preventionSteps,
        medicationNames: value.medicationNames,
        treatmentSteps: value.treatmentSteps
    };
}
async function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    imageBlob: _ExternalBlob;
    severityLevel: _SeverityLevel;
    userId: _UserId;
    confidenceScore: number;
    diseaseName: string;
    timestamp: _Timestamp;
}): Promise<{
    id: bigint;
    imageBlob: ExternalBlob;
    severityLevel: SeverityLevel;
    userId: UserId;
    confidenceScore: number;
    diseaseName: string;
    timestamp: Timestamp;
}> {
    return {
        id: value.id,
        imageBlob: await from_candid_ExternalBlob_n42(_uploadFile, _downloadFile, value.imageBlob),
        severityLevel: from_candid_SeverityLevel_n18(_uploadFile, _downloadFile, value.severityLevel),
        userId: value.userId,
        confidenceScore: value.confidenceScore,
        diseaseName: value.diseaseName,
        timestamp: value.timestamp
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    confirmed: null;
}): AppointmentStatus {
    return "cancelled" in value ? AppointmentStatus.cancelled : "pending" in value ? AppointmentStatus.pending : "confirmed" in value ? AppointmentStatus.confirmed : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mild: null;
} | {
    severe: null;
} | {
    moderate: null;
}): SeverityLevel {
    return "mild" in value ? SeverityLevel.mild : "severe" in value ? SeverityLevel.severe : "moderate" in value ? SeverityLevel.moderate : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    user: null;
} | {
    assistant: null;
}): ChatRole {
    return "user" in value ? ChatRole.user : "assistant" in value ? ChatRole.assistant : value;
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Appointment>): Array<Appointment> {
    return value.map((x)=>from_candid_Appointment_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChatMessage>): Array<ChatMessage> {
    return value.map((x)=>from_candid_ChatMessage_n29(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PredictionRecord>): Promise<Array<PredictionRecord>> {
    return await Promise.all(value.map(async (x)=>await from_candid_PredictionRecord_n40(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SuccessStory>): Array<SuccessStory> {
    return value.map((x)=>from_candid_SuccessStory_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DiseaseRecord>): Array<DiseaseRecord> {
    return value.map((x)=>from_candid_DiseaseRecord_n35(_uploadFile, _downloadFile, x));
}
function to_candid_AppointmentInput_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppointmentInput): _AppointmentInput {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_AppointmentStatus_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppointmentStatus): _AppointmentStatus {
    return to_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function to_candid_ChatRole_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChatRole): _ChatRole {
    return to_candid_variant_n47(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_PredictionInput_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PredictionInput): Promise<_PredictionInput> {
    return await to_candid_record_n49(_uploadFile, _downloadFile, value);
}
function to_candid_SeverityLevel_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SeverityLevel): _SeverityLevel {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    preferredDatetime: string;
    diseaseName: string;
    severity: SeverityLevel;
    phone: string;
    location: string;
}): {
    name: string;
    preferredDatetime: string;
    diseaseName: string;
    severity: _SeverityLevel;
    phone: string;
    location: string;
} {
    return {
        name: value.name,
        preferredDatetime: value.preferredDatetime,
        diseaseName: value.diseaseName,
        severity: to_candid_SeverityLevel_n12(_uploadFile, _downloadFile, value.severity),
        phone: value.phone,
        location: value.location
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    imageBlob: ExternalBlob;
    plantType: string;
}): Promise<{
    imageBlob: _ExternalBlob;
    plantType: string;
}> {
    return {
        imageBlob: await to_candid_ExternalBlob_n45(_uploadFile, _downloadFile, value.imageBlob),
        plantType: value.plantType
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SeverityLevel): {
    mild: null;
} | {
    severe: null;
} | {
    moderate: null;
} {
    return value == SeverityLevel.mild ? {
        mild: null
    } : value == SeverityLevel.severe ? {
        severe: null
    } : value == SeverityLevel.moderate ? {
        moderate: null
    } : value;
}
function to_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChatRole): {
    user: null;
} | {
    assistant: null;
} {
    return value == ChatRole.user ? {
        user: null
    } : value == ChatRole.assistant ? {
        assistant: null
    } : value;
}
function to_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppointmentStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    confirmed: null;
} {
    return value == AppointmentStatus.cancelled ? {
        cancelled: null
    } : value == AppointmentStatus.pending ? {
        pending: null
    } : value == AppointmentStatus.confirmed ? {
        confirmed: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
